{ usercfg
, writeShellApplication
, git
, nixos-install-tools
, vim
}:

writeShellApplication {
  name = "dotfiles-pre-build";

  runtimeInputs = [
    git
    nixos-install-tools
    vim
  ];

  text = ''
    dotfiles_dir="${usercfg.dir.dotfiles.self}"
    if [ ! -d "$dotfiles_dir" ]; then
      git clone https://github.com/rcholla/.files.git "$dotfiles_dir"
    fi

    vim "$dotfiles_dir/flake.nix"

    temp_hardware_config="$dotfiles_dir/hardware-configuration.temp.nix"
    nixos-generate-config --show-hardware-config > "$temp_hardware_config"

    echo "
      > '$temp_hardware_config' has been generated by \`nixos-generate-config\`.
      > You should update your hardware configuration manually by using autogenerated file as a reference.
      > After completing this step, you can build the entire config by running \`nix run github:rcholla/.files#build\`
    "
  '';
}
