{ config, lib, pkgs, usercfg, ... }:
let
  T = usercfg.themes.default;
  userpkgs.kitten-search = pkgs.fetchFromGitHub {
    owner = "trygveaa";
    repo = "kitty-kitten-search";
    rev = "0760138fad617c5e4159403cbfce8421ccdfe571";
    hash = "sha256-egisza7V5dWplRYHIYt4bEQdqXa4E7UhibyWJAup8as=";
  };
in
{
  programs.kitty = {
    enable = true;
    package = usercfg.env.terminal.pkg;
    theme = T.kitty.name;
    settings = {
      font_family = usercfg.fonts.firaCode.family;
      bold_font = "auto";
      italic_font = usercfg.fonts.mapleMono.variants.italic;
      bold_italic_font = usercfg.fonts.mapleMono.variants.boldItalic;
      font_size = "9.0";
      adjust_line_height = 0;
      adjust_column_width = 0;
      disable_ligatures = "never";
      hide_window_decorations = true;
      box_drawing_scale = "0.001, 1, 1.5, 2";
      cursor_shape = "block";
      cursor_blink_interval = -1;
      cursor_stop_blinking_after = "15.0";
      scrollback_lines = 10000;
      scrollback_pager = "less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER";
      scrollback_pager_history_size = 0;
      wheel_scroll_multiplier = "5.0";
      touch_scroll_multiplier = "1.0";
      mouse_hide_wait = "3.0";
      url_style = "single";
      open_url_with = "default";
      copy_on_select = true;
      strip_trailing_spaces = "smart";
      select_by_word_characters = ":@-./_~?&=%+#";
      click_interval = "-1.0";
      focus_follows_mouse = false;
      repaint_delay = 10;
      input_delay = 3;
      sync_to_monitor = false;
      enable_audio_bell = false;
      visual_bell_duration = "0.0";
      window_alert_on_bell = false;
      bell_on_tab = false;
      command_on_bell = "none";
      remember_window_size = true;
      initial_window_width = 640;
      initial_window_height = 400;
      enabled_layouts = "tall,*";
      window_resize_step_cells = 2;
      window_resize_step_lines = 2;
      window_border_width = "1px";
      draw_minimal_borders = true;
      window_margin_width = 0;
      single_window_margin_width = "-1000.0";
      window_padding_width = 5;
      placement_strategy = "top-left";
      confirm_os_window_close = 0;
      inactive_text_alpha = "1.0";
      resize_debounce_time = "0.1";
      tab_bar_edge = "bottom";
      tab_bar_margin_width = "0.0";
      tab_bar_min_tabs = 2;
      tab_switch_strategy = "previous";
      tab_separator = " ┇";
      tab_title_template = "{fmt.bold}{fmt.italic}{title}";
      tab_bar_style = "powerline";
      tab_powerline_style = "angled";
      background_opacity = "0.80";
      dynamic_background_opacity = true;
      dim_opacity = "0.60";
      shell = usercfg.env.shell.name;
      editor = usercfg.env.editor.name;
      close_on_child_death = false;
      allow_remote_control = true;
      listen_on = "unix:@mykitty";
      update_check_interval = 0;
      startup_session = "none";
      clipboard_control = "write-clipboard write-primary";
      term = "xterm-kitty";
      linux_display_server = "auto";
      kitty_mod = "ctrl+shift";
      clear_all_shortcuts = true;
    };
    keybindings = {
      "kitty_mod+g" = "scroll_home";
      "kitty_mod+4" = "scroll_end";
      "kitty_mod+c" = "copy_to_clipboard";
      "kitty_mod+v" = "paste_from_clipboard";
      "kitty_mod+s" = "paste_from_selection";
      "kitty_mod+o" = "pass_selection_to_program";
      "kitty_mod+equal" = "change_font_size all +1.0";
      "kitty_mod+minus" = "change_font_size all -1.0";
      "kitty_mod+backspace" = "change_font_size all 0";
      "kitty_mod+o>d" = "set_background_opacity default";
      "kitty_mod+o>m" = "set_background_opacity +0.1";
      "kitty_mod+o>l" = "set_background_opacity -0.1";
      "kitty_mod+o>1" = "set_background_opacity 1";
      "kitty_mod+u" = "kitten unicode_input";
      "kitty_mod+escape" = "kitty_shell window";
      "kitty_mod+f11" = "toggle_fullscreen";
      "kitty_mod+f10" = "toggle_maximized";
      "kitty_mod+/" = "launch --allow-remote-control kitty +kitten kitten-search/search.py @active-kitty-window-id";
      "kitty_mod+'" = "previous_layout";
      "kitty_mod+\\" = "next_layout";
      "kitty_mod+space" = "new_window_with_cwd";
      "kitty_mod+q" = "close_window";
      "kitty_mod+]" = "next_window";
      "kitty_mod+[" = "previous_window";
      "shift+alt+k" = "move_window up";
      "shift+alt+j" = "move_window bottom";
      "shift+alt+h" = "move_window left";
      "shift+alt+l" = "move_window right";
      "kitty_mod+k" = "neighboring_window up";
      "kitty_mod+j" = "neighboring_window bottom";
      "kitty_mod+h" = "neighboring_window left";
      "kitty_mod+l" = "neighboring_window right";
      "kitty_mod+alt+r" = "start_resizing_window";
      "kitty_mod+alt+k" = "resize_window taller";
      "kitty_mod+alt+j" = "resize_window shorter";
      "kitty_mod+alt+h" = "resize_window narrower";
      "kitty_mod+alt+l" = "resize_window wider";
      "kitty_mod+right" = "next_tab";
      "kitty_mod+left" = "previous_tab";
      "kitty_mod+t" = "new_tab_with_cwd";
      "kitty_mod+alt+right" = "move_tab_forward";
      "kitty_mod+alt+left" = "move_tab_backward";
      "kitty_mod+r" = "set_tab_title";
    };
  };

  xdg.configFile = {
    "kitty/kitten-search/search.py".source = "${userpkgs.kitten-search}/search.py";
    "kitty/kitten-search/scroll_mark.py".source = "${userpkgs.kitten-search}/scroll_mark.py";
    "kdeglobals".source = (pkgs.formats.ini { }).generate "kdeglobals" { General.TerminalApplication = "kitty"; };
  };
}
