return {
  "folke/which-key.nvim",
  cmd = "WhichKey",
  keys = "<leader>",
  opts = {
    plugins = {
      marks = true,
      registers = true,
      spelling = { enabled = true },
      presets = {
        operators = false,
        motions = false,
        text_objects = false,
        windows = false,
        nav = false,
        z = true,
        g = true,
      },
    },
    window = {
      border = "rounded",
      position = "bottom",
      margin = { 1, 0, 1, 0 },
      padding = { 2, 2, 2, 2 },
    },
    layout = {
      align = "center",
    },
    ignore_missing = true,
    show_keys = false,
    disable = {
      filetypes = { "TelescopePrompt", "neo-tree" },
    },
  },
  config = function(_, opts)
    local whichkey = require("which-key")

    whichkey.setup(opts)

    whichkey.register({
      ["c"] = { ":lua vim.lsp.codelens.run()<CR>", "Codelens" },
      ["a"] = { ":Lspsaga code_action<CR>", "Code Action" },
      ["R"] = { ":IncRename ", "IncRename" },
      ["e"] = { ":Neotree toggle<CR>", "Neotree" },
      -- stylua: ignore
      ["f"] = { ":lua require('telescope.builtin').find_files(require('telescope.themes').get_dropdown({ previewer = false, hidden = true }))<CR>", "Files" },
      ["m"] = { ":Telescope media_files<CR>", "Media Files" },
      ["F"] = { ":Telescope live_grep<CR>", "Live Grep" },
      ["p"] = { ":Telescope projects<CR>", "Projects" },
      g = {
        name = "Git",
        l = { ":lua require('gitsigns').blame_line()<CR>", "Blame line" },
        j = { ":lua require('gitsigns').next_hunk()<CR>", "Next hunk" },
        k = { ":lua require('gitsigns').prev_hunk()<CR>", "Prev hunk" },
        p = { ":lua require('gitsigns').preview_hunk()<CR>", "Preview hunk" },
        r = { ":lua require('gitsigns').reset_hunk()<CR>", "Reset hunk" },
        R = { ":lua require('gitsigns').reset_buffer()<CR>", "Reset buffer" },
        s = { ":lua require('gitsigns').stage_hunk()<CR>", "Stage hunk" },
        u = { ":lua require('gitsigns').undo_stage_hunk()<CR>", "Undo stage hunk" },
        o = { ":Telescope git_status<CR>", "Status" },
        b = { ":Telescope git_branches<CR>", "Branches" },
        c = { ":Telescope git_commits<CR>", "Commits" },
      },
      d = {
        name = "DAP",
        b = { ":lua require('persistent-breakpoints.api').toggle_breakpoint()<CR>", "Toggle breakpoint" },
        c = { ":lua require('persistent-breakpoints.api').clear_all_breakpoints()<CR>", "Clear breakpoints" },
        -- stylua: ignore
        C = { ":lua require('persistent-breakpoints.api').set_conditional_breakpoint()<CR>", "Set conditional breakpoint" },
        h = { ":lua require('dap').continue()<CR>", "Continue" },
        k = { ":lua require('dap').step_out()<CR>", "Step out" },
        l = { ":lua require('dap').step_into()<CR>", "Step into" },
        j = { ":lua require('dap').step_over()<CR>", "Step over" },
        _ = { ":lua require('dap').run_last()<CR>", "Run last" },
        u = { ":lua require('dapui').toggle()<CR>", "DAP UI" },
        s = { ":lua require('dapui').float_element('scopes')<CR>", "Scopes" },
        S = { ":lua require('dapui').float_element('stacks')<CR>", "Stacks" },
        w = { ":lua require('dapui').float_element('watches')<CR>", "Watches" },
        B = { ":lua require('dapui').float_element('breakpoints')<CR>", "Breakpoints" },
        r = { ":lua require('dapui').float_element('repl')<CR>", "Repl" },
        e = { ":lua require('dap').set_exception_breakpoints({ 'all' })<CR>", "Set exception breakpoints" },
      },
      t = {
        name = "Test",
        r = { ":lua require('neotest').run.run()<CR>", "Run nearest test" },
        f = { ":lua require('neotest').run.run(vim.fn.expand('%'))<CR>", "Run current file" },
        d = { ":lua require('neotest').run.run({ strategy = 'dap' })<CR>", "Debug nearest test" },
        s = { ":lua require('neotest').run.stop()<CR>", "Stop nearest test" },
        a = { ":lua require('neotest').run.attach()<CR>", "Attach to nearest test" },
        o = { ":lua require('neotest').output.open({ enter = true })<CR>", "Output" },
        S = { ":lua require('neotest').summary.toggle()<CR>", "Summary" },
      },
      r = {
        name = "Rust",
        r = { ":RustLsp runnables<CR>", "Runnables" },
        d = { ":RustLsp debuggables<CR>", "Debuggables" },
        m = { ":RustLsp expandMacro<CR>", "Expand macro" },
        M = { ":RustLsp rebuildProcMacros<CR>", "Rebuild proc macros" },
        a = { ":RustLsp hover actions<CR>", "Hover actions" },
        e = { ":RustLsp explainError<CR>", "Explain error" },
        c = { ":RustLsp openCargo<CR>", "Open Cargo.toml" },
        p = { ":RustLsp parentModule<CR>", "Parent module" },
        s = { ":RustLsp ssr<CR>", "Structural search replace" },
        g = { ":RustLsp crateGraph<CR>", "Crate graph" },
        t = { ":RustLsp syntaxTree<CR>", "Syntax tree" },
        f = { ":RustLsp flyCheck<CR>", "Fly check" },
      },
      h = {
        name = "Haskell",
        e = { ":lua require('haskell-tools').lsp.buf_eval_all()<CR>", "Evaluate all" },
        h = { ":lua require('haskell-tools').hoogle.hoogle_signature()<CR>", "Hoogle signature" },
        R = { ":lua require('haskell-tools').repl.toggle()<CR>", "Repl" },
        t = { ":lua require('haskell-tools').tags.generate_project_tags()<CR>", "Generate project tags" },
        T = { ":lua require('haskell-tools').tags.generate_package_tags()<CR>", "Generate package tags" },
        l = {
          name = "LSP",
          s = { ":lua require('haskell-tools').lsp.start()<CR>", "Start LSP client" },
          S = { ":lua require('haskell-tools').lsp.stop()<CR>", "Stop LSP client" },
          r = { ":lua require('haskell-tools').lsp.restart()<CR>", "Restart LSP client" },
        },
        r = {
          name = "Repl",
          r = { ":lua require('haskell-tools').repl.reload()<CR>", "Reload repl" },
          q = { ":lua require('haskell-tools').repl.quit()<CR>", "Quit repl" },
          T = { ":lua require('haskell-tools').repl.cword_type()<CR>", "Query type" },
          i = { ":lua require('haskell-tools').repl.cword_info()<CR>", "Query info" },
        },
        p = {
          name = "Project",
          f = { ":lua require('haskell-tools').project.open_project_file()<CR>", "Open project file" },
          y = { ":lua require('haskell-tools').project.open_package_yaml()<CR>", "Open package.yaml" },
          c = { ":lua require('haskell-tools').project.open_package_cabal()<CR>", "Open *.cabal" },
          t = { ":lua require('haskell-tools').project.telescope_package_files()<CR>", "Search files" },
          T = { ":lua require('haskell-tools').project.telescope_package_grep()<CR>", "Live grep" },
        },
      },
      o = {
        name = "Obsidian",
        o = { ":ObsidianOpen<CR>", "Open" },
        n = { ":ObsidianNew<CR>", "New note" },
        q = { ":ObsidianQuickSwitch<CR>", "Quick switch" },
        f = { ":ObsidianFollowLink<CR>", "Follow link" },
        b = { ":ObsidianBacklinks<CR>", "Backlinks" },
        t = { ":ObsidianToday<CR>", "Today" },
        y = { ":ObsidianYesterday<CR>", "Yesterday" },
        T = { ":ObsidianTemplate<CR>", "Template" },
        s = { ":ObsidianSearch<CR>", "Search" },
      },
    }, {
      mode = "n",
      prefix = "<leader>",
      buffer = nil,
      silent = true,
      noremap = true,
      nowait = true,
    })

    whichkey.register({
      o = {
        name = "Obsidian",
        l = { ":ObsidianLink<CR>", "Link" },
        L = { ":ObsidianLinkNew<CR>", "Link new" },
      },
    }, {
      mode = "v",
      prefix = "<leader>",
      buffer = nil,
      silent = true,
      noremap = true,
      nowait = true,
    })
  end,
}
